version: '3.9'
services:
  pgdatabase:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - postgres-default

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    volumes:
      - "pgadmin:/var/lib/pgadmin:rw"
    networks:
      - postgres-default

  ingest:
    build: .
    networks:
      - postgres-default
    command: ["--user=root", "--password=root", "--host=postgres", "--port=5432", "--db=ny_taxi", "--table-name=yellow_taxi_trips", "--url=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-01.parquet"]
    
  
networks:
  postgres-default:
    driver: bridge

volumes:
  pgadmin:




