# docker compose file for our local postgres and pgadmin setup
version: '3.9'
services:
  pgdatabase:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - postgres-default
      - airflow

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    volumes:
      - "pgadmin:/var/lib/pgadmin:rw"
    networks:
      - postgres-default
    
  
networks:
  postgres-default:
    driver: bridge
  airflow:
    external:
      name: airflow_default

volumes:
  pgadmin:




